config/routes.rb
Rails.application.routes.draw do
  get 'quran/q01'

  get 'quran/q02'

  get 'inggeris/anggotabadan'

  get 'inggeris/anggotabadan2'

  get 'inggeris/anggotakeluarga'

  get 'inggeris/anggotakeluarga2'

  get 'inggeris/arah'

  get 'inggeris/bentuk'

  get 'inggeris/binatangliar'

  get 'inggeris/binatangperliharaan'

  get 'inggeris/buahbuahan'

  get 'inggeris/buahbuahan2'

  get 'inggeris/bulanislam'

  get 'inggeris/bulanislamv2'

  get 'inggeris/bulanmasihi'

  get 'inggeris/bulanmasihiv2'

  get 'inggeris/bunga'

  get 'inggeris/burung'

  get 'inggeris/fenomenaalam'

  get 'inggeris/hari'

  get 'inggeris/hari2'

  get 'inggeris/hobi'

  get 'inggeris/index'

  get 'inggeris/kenderaan'

  get 'inggeris/makanan'

  get 'inggeris/makanan2'

  get 'inggeris/masa'

  get 'inggeris/musim'

  get 'inggeris/negeridimalaysia'

  get 'inggeris/nombor1'

  get 'inggeris/nombor2'

  get 'inggeris/nombor3'

  get 'inggeris/nombor4'

  get 'inggeris/nombor5'

  get 'inggeris/organdalaman'

  get 'inggeris/pakaian'

  get 'inggeris/partikel'

  get 'inggeris/partikel2'

  get 'inggeris/partikel3'

  get 'inggeris/partikel4'

  get 'inggeris/partikel5'

  get 'inggeris/partikel6'

  get 'inggeris/pekerjaan'

  get 'inggeris/pekerjaan2'

  get 'inggeris/penyakit'

  get 'inggeris/peralatan'

  get 'inggeris/peralatan2'

  get 'inggeris/peralatan3'

  get 'inggeris/peralatan4'

  get 'inggeris/sayursayuran'

  get 'inggeris/sayursayuran2'

  get 'inggeris/seranggahaiwankecil'

  get 'inggeris/seranggahaiwankecil2'

  get 'inggeris/warna'

  get 'jawi/anggotabadan'

  get 'jawi/anggotabadan2'

  get 'jawi/anggotakeluarga'

  get 'jawi/anggotakeluarga2'

  get 'jawi/arah'

  get 'jawi/bentuk'

  get 'jawi/binatangliar'

  get 'jawi/binatangperliharaan'

  get 'jawi/buahbuahan'

  get 'jawi/buahbuahan2'

  get 'jawi/bulanislam'

  get 'jawi/bulanislamv2'

  get 'jawi/bulanmasihi'

  get 'jawi/bulanmasihiv2'

  get 'jawi/bunga'

  get 'jawi/burung'

  get 'jawi/fenomenaalam'

  get 'jawi/hari'

  get 'jawi/hari2'

  get 'jawi/hobi'

  get 'jawi/index'

  get 'jawi/kenderaan'

  get 'jawi/makanan'

  get 'jawi/makanan2'

  get 'jawi/masa'

  get 'jawi/musim'

  get 'jawi/negeridimalaysia'

  get 'jawi/nombor1'

  get 'jawi/nombor2'

  get 'jawi/nombor3'

  get 'jawi/nombor4'

  get 'jawi/nombor5'

  get 'jawi/organdalaman'

  get 'jawi/pakaian'

  get 'jawi/partikel'

  get 'jawi/partikel2'

  get 'jawi/partikel3'

  get 'jawi/partikel4'

  get 'jawi/partikel5'

  get 'jawi/partikel6'

  get 'jawi/pekerjaan'

  get 'jawi/pekerjaan2'

  get 'jawi/penyakit'

  get 'jawi/peralatan'

  get 'jawi/peralatan2'

  get 'jawi/peralatan3'

  get 'jawi/peralatan4'

  get 'jawi/sayursayuran'

  get 'jawi/sayursayuran2'

  get 'jawi/seranggahaiwankecil'

  get 'jawi/seranggahaiwankecil2'

  get 'jawi/warna'

  get 'quranic/q01'

  get 'quranic/q02'

  get 'quranic/q03'

  get 'quranic/q04'

  get 'quranic/q05'

  get 'quranic/q06'

  get 'quranic/q07'

  get 'quranic/q08'

  get 'quranic/q09'

  get 'quranic/q10'

  get 'quranic/q11'

  get 'quranic/q12'

  get 'quranic/q13'

  get 'quranic/q14'

  get 'quranic/q15'

  get 'quranic/q16'

  get 'quranic/q17'

  get 'quranic/q18'

  get 'quranic/q19'

  get 'quranic/q20'

  get 'quranic/q21'

  get 'quranic/q22'

  get 'quranic/q23'

  get 'quranic/q24'

  get 'quranic/q25'

  get 'quranic/q26'

  get 'quranic/q27'

  get 'quranic/q28'

  get 'quranic/q29'

  get 'quranic/q30'

  get 'quranic/q31'

  get 'quranic/q32'

  get 'quranic/q33'

  get 'quranic/q34'

  get 'quranic/q35'

  get 'quranic/q36'

  get 'quranic/q37'

  get 'quranic/q38'

  get 'quranic/q39'

  get 'quranic/q40'

  get 'quranic/q41'

  get 'quranic/q42'

  get 'quranic/q43'

  get 'quranic/q44'

  get 'quranic/q45'

  get 'quranic/q46'

  get 'quranic/q47'

  get 'quranic/q48'

  get 'quranic/q49'

  get 'quranic/q50'

  get 'quranic/q51'

  get 'quranic/q52'

  get 'quranic/q53'

  get 'quranic/q54'

  get 'quranic/q55'

  get 'quranic/q56'

  get 'quranic/q57'

  get 'quranic/q58'

  get 'quranic/q59'

  get 'bahasa_arab/anggotabadan'

  get 'bahasa_arab/anggotabadan2'

  get 'bahasa_arab/anggotakeluarga'

  get 'bahasa_arab/arah'

  get 'bahasa_arab/bentuk'

  get 'bahasa_arab/binatangliar'

  get 'bahasa_arab/binatangperliharaan'

  get 'bahasa_arab/buahbuahan'

  get 'bahasa_arab/buahbuahan2'

  get 'bahasa_arab/bulanislam'

  get 'bahasa_arab/bulanislamv2'

  get 'bahasa_arab/bulanmasihi'

  get 'bahasa_arab/bulanmasihiv2'

  get 'bahasa_arab/bunga'

  get 'bahasa_arab/burung'

  get 'bahasa_arab/fenomenaalam'

  get 'bahasa_arab/hari'

  get 'bahasa_arab/hobi'

  get 'bahasa_arab/kenderaan'

  get 'bahasa_arab/makanan'

  get 'bahasa_arab/makanan2'

  get 'bahasa_arab/masa'

  get 'bahasa_arab/musim'

  get 'bahasa_arab/negeridimalaysia'

  get 'bahasa_arab/nombor1'

  get 'bahasa_arab/nombor2'

  get 'bahasa_arab/nombor3'

  get 'bahasa_arab/nombor4'

  get 'bahasa_arab/nombor5'

  get 'bahasa_arab/organdalaman'

  get 'bahasa_arab/pakaian'

  get 'bahasa_arab/partikel'

  get 'bahasa_arab/partikel2'

  get 'bahasa_arab/partikel3'

  get 'bahasa_arab/partikel4'

  get 'bahasa_arab/partikel5'

  get 'bahasa_arab/partikel6'

  get 'bahasa_arab/pekerjaan'

  get 'bahasa_arab/pekerjaan2'

  get 'bahasa_arab/penyakit'

  get 'bahasa_arab/peralatan'

  get 'bahasa_arab/peralatan2'

  get 'bahasa_arab/peralatan3'

  get 'bahasa_arab/peralatan4'

  get 'bahasa_arab/sayursayuran'

  get 'bahasa_arab/sayursayuran2'

  get 'bahasa_arab/seranggahaiwankecil'

  get 'bahasa_arab/seranggahaiwankecil2'

  get 'bahasa_arab/warna'

  root 'static_pages#home' # => root_path
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'

  # => contact_path

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'application#hello'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Hadza Min Fadhli Rabbi</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path   %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "falah.org", root_url, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Bahasa <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Quran", quran_q01_path %></li>
                <li><%= link_to "Quranic", quranic_q01_path %></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header"></li>
                <li><%= link_to "Arab", bahasa_arab_hari_path %></li>
                <li><%= link_to "Jawi", jawi_hari_path %></li>
                <li><%= link_to "Inggeris", inggeris_hari_path %></li>
              </ul>
            </li>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/_inggeris_right.html.erb
</br>
<div class="list-group">
<%= link_to "Anggota Badan",inggeris_anggotabadan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Anggota Badan 2",inggeris_anggotabadan2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Anggota Keluarga",inggeris_anggotakeluarga_path,class: "list-group-item list-group-ite" %>
<%= link_to "Arah",inggeris_arah_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Bentuk",inggeris_bentuk_path,class: "list-group-item list-group-ite" %>
<%= link_to "Binatang Liar",inggeris_binatangliar_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Binatang Perliharaan",inggeris_binatangperliharaan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Buah-buahan",inggeris_buahbuahan_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Buah-buahan 2",inggeris_buahbuahan2_path,class: "list-group-item list-group-ite" %>
<% link_to "Bulan Islam",inggeris_bulanislam_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<% link_to "Bulan Masihi",inggeris_bulanmasihi_path,class: "list-group-item list-group-ite" %>
<%= link_to "Bunga",inggeris_bunga_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Burung",inggeris_burung_path,class: "list-group-item list-group-ite" %>
<%= link_to "Fenomena Alam",inggeris_fenomenaalam_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Hari",inggeris_hari_path,class: "list-group-item list-group-ite" %>
<%= link_to "Hobi",inggeris_hobi_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Kenderaan",inggeris_kenderaan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Makanan",inggeris_makanan_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Makanan 2",inggeris_makanan2_path,class: "list-group-item list-group-ite" %>
<%= link_to "Masa",inggeris_masa_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Musim",inggeris_musim_path,class: "list-group-item list-group-ite" %>
<%= link_to "Negeri di Malaysia",inggeris_negeridimalaysia_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Nombor1",inggeris_nombor1_path,class: "list-group-item list-group-ite" %>
<%= link_to "Nombor 2",inggeris_nombor2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Nombor 3",inggeris_nombor3_path,class: "list-group-item list-group-ite" %>
<%= link_to "Nombor 4",inggeris_nombor4_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Nombor 5",inggeris_nombor5_path,class: "list-group-item list-group-ite" %>
<%= link_to "Organ Dalaman",inggeris_organdalaman_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Pakaian",inggeris_pakaian_path,class: "list-group-item list-group-ite" %>
<%= link_to "Partikel",inggeris_partikel_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Partikel 2",inggeris_partikel2_path,class: "list-group-item list-group-ite" %>
<%= link_to "Partikel 3",inggeris_partikel3_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Partikel 4",inggeris_partikel4_path,class: "list-group-item list-group-ite" %>
<%= link_to "Partikel 5",inggeris_partikel5_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Partikel 6",inggeris_partikel6_path,class: "list-group-item list-group-ite" %>
<%= link_to "Pekerjaan",inggeris_pekerjaan_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Pekerjaan 2",inggeris_pekerjaan2_path,class: "list-group-item list-group-ite" %>
<%= link_to "Penyakit",inggeris_penyakit_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Peralatan",inggeris_peralatan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Peralatan 2",inggeris_peralatan2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Peralatan 3",inggeris_peralatan3_path,class: "list-group-item list-group-ite" %>
<%= link_to "Peralatan 4",inggeris_peralatan4_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Sayur-sayuran",inggeris_sayursayuran_path,class: "list-group-item list-group-ite" %>
<%= link_to "Sayur-sayuran 2",inggeris_sayursayuran2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Serangga haiwan Kecil",inggeris_seranggahaiwankecil_path,class: "list-group-item list-group-ite" %>
<%= link_to "Serangga haiwan Kecil 2",inggeris_seranggahaiwankecil2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Warna",inggeris_warna_path,class: "list-group-item list-group-ite" %>

</div>

app/views/layouts/_jawi_right.html.erb
</br>
<div class="list-group">
<%= link_to "Anggota Badan",jawi_anggotabadan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Anggota Badan 2",jawi_anggotabadan2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Anggota Keluarga",jawi_anggotakeluarga_path,class: "list-group-item list-group-ite" %>
<%= link_to "Arah",jawi_arah_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Bentuk",jawi_bentuk_path,class: "list-group-item list-group-ite" %>
<%= link_to "Binatang Liar",jawi_binatangliar_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Binatang Perliharaan",jawi_binatangperliharaan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Buah-buahan",jawi_buahbuahan_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Buah-buahan 2",jawi_buahbuahan2_path,class: "list-group-item list-group-ite" %>
<% link_to "Bulan Islam",jawi_bulanislam_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Bulan Masihi",jawi_bulanmasihi_path,class: "list-group-item list-group-ite" %>
<%= link_to "Bunga",jawi_bunga_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Burung",jawi_burung_path,class: "list-group-item list-group-ite" %>
<%= link_to "Fenomena Alam",jawi_fenomenaalam_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Hari",jawi_hari_path,class: "list-group-item list-group-ite" %>
<%= link_to "Hobi",jawi_hobi_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Kenderaan",jawi_kenderaan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Makanan",jawi_makanan_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Makanan 2",jawi_makanan2_path,class: "list-group-item list-group-ite" %>
<%= link_to "Masa",jawi_masa_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Musim",jawi_musim_path,class: "list-group-item list-group-ite" %>
<%= link_to "Negeri di Malaysia",jawi_negeridimalaysia_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Nombor1",jawi_nombor1_path,class: "list-group-item list-group-ite" %>
<%= link_to "Nombor 2",jawi_nombor2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Nombor 3",jawi_nombor3_path,class: "list-group-item list-group-ite" %>
<%= link_to "Nombor 4",jawi_nombor4_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Nombor 5",jawi_nombor5_path,class: "list-group-item list-group-ite" %>
<%= link_to "Organ Dalaman",jawi_organdalaman_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Pakaian",jawi_pakaian_path,class: "list-group-item list-group-ite" %>
<%= link_to "Partikel",jawi_partikel_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Partikel 2",jawi_partikel2_path,class: "list-group-item list-group-ite" %>
<%= link_to "Partikel 3",jawi_partikel3_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Partikel 4",jawi_partikel4_path,class: "list-group-item list-group-ite" %>
<%= link_to "Partikel 5",jawi_partikel5_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Partikel 6",jawi_partikel6_path,class: "list-group-item list-group-ite" %>
<%= link_to "Pekerjaan",jawi_pekerjaan_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Pekerjaan 2",jawi_pekerjaan2_path,class: "list-group-item list-group-ite" %>
<%= link_to "Penyakit",jawi_penyakit_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Peralatan",jawi_peralatan_path,class: "list-group-item list-group-ite" %>
<%= link_to "Peralatan 2",jawi_peralatan2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Peralatan 3",jawi_peralatan3_path,class: "list-group-item list-group-ite" %>
<%= link_to "Peralatan 4",jawi_peralatan4_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Sayur-sayuran",jawi_sayursayuran_path,class: "list-group-item list-group-ite" %>
<%= link_to "Sayur-sayuran 2",jawi_sayursayuran2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Serangga haiwan Kecil",jawi_seranggahaiwankecil_path,class: "list-group-item list-group-ite" %>
<%= link_to "Serangga haiwan Kecil 2",jawi_seranggahaiwankecil2_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Warna",jawi_warna_path,class: "list-group-item list-group-ite" %>

</div>

app/views/layouts/_quran_right.html.erb
</br>
<div class="list-group">
<%= link_to "Part 01",quran_q01_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 02",quran_q02_path,class: "list-group-item list-group-item-action list-group-item-info" %>
</div>

app/views/layouts/_quranic_right.html.erb
</br>
<div class="list-group">
<%= link_to "Part 01",quranic_q01_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 02",quranic_q02_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 03",quranic_q03_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 04",quranic_q04_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 05",quranic_q05_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 06",quranic_q06_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 07",quranic_q07_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 08",quranic_q08_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 09",quranic_q09_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 10",quranic_q10_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 11",quranic_q11_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 12",quranic_q12_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 13",quranic_q13_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 14",quranic_q14_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 15",quranic_q15_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 16",quranic_q16_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 17",quranic_q17_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 18",quranic_q18_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 19",quranic_q19_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 20",quranic_q20_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 21",quranic_q21_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 22",quranic_q22_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 23",quranic_q23_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 24",quranic_q24_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 25",quranic_q25_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 26",quranic_q26_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 27",quranic_q27_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 28",quranic_q28_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 29",quranic_q29_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 30",quranic_q30_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 31",quranic_q31_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 32",quranic_q32_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 33",quranic_q33_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 34",quranic_q34_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 35",quranic_q35_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 36",quranic_q36_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 37",quranic_q37_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 38",quranic_q38_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 39",quranic_q39_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 40",quranic_q40_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 41",quranic_q41_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 42",quranic_q42_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 43",quranic_q43_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 44",quranic_q44_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 45",quranic_q45_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 46",quranic_q46_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 47",quranic_q47_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 48",quranic_q48_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 49",quranic_q49_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 50",quranic_q50_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 51",quranic_q51_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 52",quranic_q52_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 53",quranic_q53_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 54",quranic_q54_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 55",quranic_q55_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 56",quranic_q56_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 57",quranic_q57_path,class: "list-group-item list-group-ite" %>
<%= link_to "Part 58",quranic_q58_path,class: "list-group-item list-group-item-action list-group-item-info" %>
<%= link_to "Part 59",quranic_q59_path,class: "list-group-item list-group-ite" %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->    